version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    networks:
      - db-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - db-network


networks: 
  db-network:
    driver: bridge